Code review 2
timofeev-28/purpleSchool-js-basic pull request #3
Opened 2024-09-17 10:02 UTC by timofeev-28

2024-09-18 14:32 UTC, GitEsense requested changes
Функцию "Crypto" нужно поменять, в остальном "ок"

2024-09-18 14:32 UTC, GitEsense commented on 8-crypto/8-crypto.js
> +console.log(checkResult);
А давайте сделаем простенько одной функцией, чтобы и обратимость сразу была, т.е. у нас есть всего ДВЕ функции:
1. функция "crypto"
2. функция "check", при этом она ничего не преобразует, использует лишь использует обратимость первой


т.е.
```js
function check(encrypt, original) {
   if(!encrypt || !original) {
       return false;
   }

   return original === crypto(encrypt);
}
```

и при выводе "тестов" будет следующее:
```js
const p = 'password';
const e = crypto(p); // 'ssapdorw'
const d = crypto(e); // 'password'

console.log(p, e, d, p === d); // 'password', 'ssapdorw', 'password', true;
console.log(check(e,p)) // true

2024-09-18 14:32 UTC, GitEsense commented on 7-converter/7-converter.js
> +}
предложу вот такие вот варианты в качестве альтернативных вариантов решения:
**Вариант №1:**
```js
function converter(sum, currency, targetCurrency) {
    const USD = 90;
    const EUR = 100;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * USD;
                case 'EUR':
                    return (sum * USD) / EUR;
                default:
                    return null;
            }
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * EUR;
                case 'USD':
                    return (sum * EUR) / USD;
                default:
                    return null;
            }
        case 'RUB':
            switch (targetCurrency) {
                case 'USD':
                    return sum / USD;
                case 'EUR':
                    return sum / EUR;
                default:
                    return null;
            }
        default:
            return null;
    }
}
```

**Вариант №2:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = ['RUB', 'EUR', 'USD'];
    const USD = 91.33;
    const RUB = 1;
    const EUR = 112.33;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();
    const icon = getTargetCurrencyIcon(targetCurrency);

    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }
    if (!ALLOW_CURRENCY_LIST.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!ALLOW_CURRENCY_LIST.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    
    let value = null;

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, USD, RUB); break;
                case 'EUR': value = convertSum(sum, USD, EUR); break;
            }; break;
        case 'RUB':
            switch (targetCurrency) {
                case 'USD': value = convertSum(sum, RUB, USD); break;
                case 'EUR': value = convertSum(sum, RUB, EUR); break;
            }; break;
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, EUR, RUB); break;
                case 'USD': value = convertSum(sum, EUR, USD); break;
            }; break;
    }

    return messageTemplate(value, icon)
}
```

**Вариант №3:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = [['RUB', 1], ['EUR', 112.33], ['USD', 91.33]];
    const flatList = ALLOW_CURRENCY_LIST.flat();
    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    if (!flatList.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!flatList.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    const icon = getTargetCurrencyIcon(targetCurrency);
    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }

    const currentIndex = flatList.indexOf(currency) / 2;
    const targetIndex = flatList.indexOf(targetCurrency) / 2;
    const [, currentValue] = ALLOW_CURRENCY_LIST[currentIndex];
    const [, targetValue] = ALLOW_CURRENCY_LIST[targetIndex];
    const result = convertSum(sum, currentValue, targetValue)
    return messageTemplate(result, icon);
}
```

2024-09-18 14:32 UTC, GitEsense commented on 9-sort-loops/9-sort-loops.js
> +console.log(sortElements(arr, increment));
Всё хорошо, только у нас идёт модификация исходного массива...
хорошо бы, если бы исходный массив не изменялся

Вот вариант реализации с направлением и без модификации исходного массива

```js
const numbers = Array.from({ length: 10 }, () => {
    const max = 100;
    const min = -100;
    const randomNumber = Math.ceil(Math.random() * (max - min)) + min;
    return randomNumber
});

function sortArray(incomingArray, desc = false) {
    const array = [...incomingArray];
    for (let i = 0; i < array.length; i++) {
        for (let j = i; j < array.length; j++) {
            const isExchange = desc ? array[i] < array[j] : array[i] > array[j]
            if (isExchange) {
                [array[i], array[j]] = [array[j], array[i]];
            }
        }
    }
    return array;
}

console.log(numbers);
console.log('Отсортированный по возрастанию массив:', sortArray(numbers));
console.log('Отсортированный по убыванию массив:', sortArray(numbers, true));

2024-09-18 14:32 UTC, GitEsense commented on 9-sort-loops/9-sort-loops.js
> +                arr[j] = el;
Вот тут можно использовать трюк обмена переменными
https://learn.javascript.ru/destructuring-assignment

2024-09-20 10:25 UTC, timofeev-28 commented on 8-crypto/8-crypto.js
> +console.log(checkResult);
Спасибо, не до конца понял задание

2024-09-20 20:17 UTC, timofeev-28 commented on 7-converter/7-converter.js
> +}
Большое спасибо за примеры, переделал, как понравилось

2024-09-23 15:41 UTC, GitEsense approved these changes

2024-09-23 15:41 UTC, GitEsense commented on 8-crypto/8-crypto.js
> +console.log(check(original, encrypt))
перестановку делать как-то "динамически", оставляю пример для анализа:

```js
function crypt(password) {
    if (!password || !password.length) {
        return NaN;
    }
    const splitedArray = password.split('');
    if (splitedArray.length < 8) {
        return false;
    }

    const middleIndex = Math.floor(splitedArray.length / 2);
    const firstHalf = splitedArray.slice(0, middleIndex).reverse();
    const secondHalf = splitedArray.slice(middleIndex).reverse();
    const length = secondHalf.length;
    [secondHalf[1], secondHalf[length - 2]] = [secondHalf[length - 2], secondHalf[1]];

    const encryptedPassword = firstHalf.concat(secondHalf);
    return encryptedPassword.join('');
}

function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypt(encryptedPassword);
}

function getRandomNumber(min = 0, max = 86) {
    return Math.ceil(Math.random() * (max - min)) + min;
}

function getRandomPassword(length = 12) {
    const symbolArray = Array.from({ length: 87 }, (_, index) => String.fromCharCode(index + 33));
    console.log(symbolArray);
    const password = Array.from({ length }, () => symbolArray[getRandomNumber()]);
    return password.join('');
}

/*
    logging and test function with console
*/

const password = getRandomPassword();
const encrypted = crypt(password);

console.log('Пароль:', password);
console.log('Зашифрованный пароль:', encrypted);
console.log('Проверка пароля:', checkPassword(encrypted, password));

const password2 = getRandomPassword();
const encrypted2 = crypt(password2).substring(1);

console.log('Пароль:', password2);
console.log('Зашифрованный пароль:', encrypted2);
console.log('Проверка пароля:', checkPassword(encrypted2, getRandomPassword()));
```

2024-09-24 08:49 UTC, merged